### PR TITLE
bug fixes and enhancements

### LINKED ISSUE #12: Support cross regional buckets for all all IBM Cloud locations
Cross regional buckets can be created in one of the following IBM Cloud locations:
- `us-geo` 
- `ap-geo`
- `eu-geo`

The training framework currently only supports `us-geo`.

### LINKED ISSUE #13: Enhance training configuration summary display
Current output:

```
Training configuration summary:
 Training run name   : <training run name>
 Training data bucket : <input bucket name>
 Results bucket    : <input bucket name>
 Model-building archive: <zip archive name>
```

Also display the following to aid with troubleshooting:
- Cloud object Storage endpoint URL
- WML endpoint URL
- Compute configuration

### PR DESCRIPTION
**Pull request by ptitzler**
The location test will be only performed if one of the following commands is specified:
train_max_model.py ...-training-config.yaml **train**
train_max_model.py ...-training-config.yaml **package**

Closes #12 
Closes #13

### CODE REVIEW

**Comment by ptitzler** [comment]
Tested using the following ML service locations:
- us-south (OK)
- eu-de (OK)
- jp-tok (OK)
- eu-gb (OK)

**Comment by SSaishruthi** [comment]
@ptitzler 

Code change looks good to me but I have below questions.

1) Do we have a list of possible endpoint URL? Just to make sure all the endpoints start with either `us-south` or `eu-gb`.

2) Are we going to let the user provide the endpoint URL? In setup, we are not letting the user provide URL.

**Comment by ptitzler** [comment]
> * Are we going to let the user provide the endpoint URL? In setup, we are not letting the user provide URL.

There is no need. The URL is already included in the service credentials:

```
$ ibmcloud resource service-key "my-wml-service-key"

Name:          Service credentials-WML   
ID:            ...   
Created At:    Thu Mar 26 03:46:57 UTC 2020   
State:         active   
Credentials:                                   
               apikey:                   ...    
               iam_apikey_description:   Auto-generated for key ...      
               iam_apikey_name:          Service credentials-WML      
               iam_role_crn:             crn:v1:bluemix:public:iam::::serviceRole:Writer      
               iam_serviceid_crn:        ...
               instance_id:              ...   
               url:                      https://eu-de.ml.cloud.ibm.com    
```

I'm assuming the service list API call returns the information `setup` require to filter out instances that were provisioned in unsupported regions:
```
$ ibmcloud resource service-instances
Name                        Location   State    Type   
cloud-object-storage-lite   global     active   service_instance   
analyze_images              us-south   active   service_instance   
WatsonStudio                us-south   active   service_instance   
Machine Learning-free       us-south   active   service_instance   
```

> * Do we have a list of possible endpoint URL? Just to make sure all the endpoints start with either `us-south` or `eu-gb`.

I created a service instance in each region to obtain the complete host names:
image

**Review by SSaishruthi — APPROVED** [review]

**Comment by SSaishruthi** [comment]
@ptitzler Code change looks good to me. Thanks for the explanation

**Pull request merged**
